from ubuntu:16.04
MAINTAINER Samlet Wu <xiaofei.wu@gmail.com>

COPY aliyun.list /etc/apt/sources.list
# docker run -it --net=dev-net --name dev -v $HOME/works:/works \
# 	-v $HOME/caches/dev:/root ubuntu:16.04 /bin/bash

## contains: build-essential, cmake, python

RUN apt-get update -qq && apt-get install -y build-essential \
	 cmake python \
	&& apt-get clean

ENV PORT 8000
EXPOSE 8000

CMD ["/bin/bash"]
